CXX=clang++
# CC compiler is used for implicit conversion from .o to executable
CC=clang++
LDFLAGS=-lz -lboost_iostreams
CXXFLAGS=--std=c++11 -Wall 
all:math #assign struct timeExample 
timeExample:
threads:
math:
	$CXX $LDFLAGS math.o ../readcsv.o -o container
struct:
multimap:multimap.o
assign:
toybox:../time.o
clean:
	rm *.o
