CC=clang++
CXX=clang++
CXXFLAGS=-Wall -std=c++11  
LDFLAGS=-lz -lboost_iostreams
SOURCES=main.cc time.cc readcsv.cc
OBJECTS=$(SOURCES:.cc=.o)
TESTFILES=time.cc test.cc
TESTOBJECTS=$(TESTFILES:.cc=.o)
EXECUTABLE=elf
#
all: $(SOURCES) $(EXECUTABLE) 
#	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@
#
#.cc.o:
#	$(CC) $(CPPFLAGS)  $< -o $@
test: test.o $(TESTOBJECTS)
	$(CC) $(LDFLAGS) -lboost_unit_test_framework $(TESTOBJECTS) -o test 
clean:
	rm -f *.o test elf
